### PR TITLE
Update modules

### PR DESCRIPTION
**Pull request by carkod**
## Done
Update modules. 

## QA
Use this https://github.com/canonical-web-and-design/docs.ubuntu.com/pull/327

### CODE REVIEW

**Comment by nottrobin** [comment]
When trying to build the snap I'm getting:

```
Building copy 
+ snapcraftctl build
Building repo 
+ snapcraftctl build
Looking in links: /root/parts/repo/python-packages
Processing /root/parts/repo/build
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: none)
ERROR: No matching distribution found for GitPython==3.1.27
Not all dependencies where satisfied with python-packages or requirements. Resorting to fetching from PyPI.
Looking in links: /root/parts/repo/python-packages
Processing /root/parts/repo/build
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20)
ERROR: No matching distribution found for GitPython==3.1.27
Failed to run '/root/parts/repo/install/usr/bin/python3 -m pip install --user --no-compile --find-links /root/parts/repo/python-packages .': Exited with code 1.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

Dunno what to do about that.

**Comment by carkod** [comment]
> When trying to build the snap I'm getting:
> 
> ```
> Building copy 
> + snapcraftctl build
> Building repo 
> + snapcraftctl build
> Looking in links: /root/parts/repo/python-packages
> Processing /root/parts/repo/build
>   Preparing metadata (setup.py) ... done
> ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: none)
> ERROR: No matching distribution found for GitPython==3.1.27
> Not all dependencies where satisfied with python-packages or requirements. Resorting to fetching from PyPI.
> Looking in links: /root/parts/repo/python-packages
> Processing /root/parts/repo/build
>   Preparing metadata (setup.py) ... done
> ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20)
> ERROR: No matching distribution found for GitPython==3.1.27
> Failed to run '/root/parts/repo/install/usr/bin/python3 -m pip install --user --no-compile --find-links /root/parts/repo/python-packages .': Exited with code 1.
> Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
> ```
> 
> Dunno what to do about that.



> When trying to build the snap I'm getting:
> 
> ```
> Building copy 
> + snapcraftctl build
> Building repo 
> + snapcraftctl build
> Looking in links: /root/parts/repo/python-packages
> Processing /root/parts/repo/build
>   Preparing metadata (setup.py) ... done
> ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: none)
> ERROR: No matching distribution found for GitPython==3.1.27
> Not all dependencies where satisfied with python-packages or requirements. Resorting to fetching from PyPI.
> Looking in links: /root/parts/repo/python-packages
> Processing /root/parts/repo/build
>   Preparing metadata (setup.py) ... done
> ERROR: Could not find a version that satisfies the requirement GitPython==3.1.27 (from ubuntudesign-documentation-builder) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20)
> ERROR: No matching distribution found for GitPython==3.1.27
> Failed to run '/root/parts/repo/install/usr/bin/python3 -m pip install --user --no-compile --find-links /root/parts/repo/python-packages .': Exited with code 1.
> Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
> ```
> 
> Dunno what to do about that.

How are you running the module?

**Comment by anthonydillon** [comment]
@akbarkz is this still valid?

**Comment by akbarkz** [comment]
@anthonydillon Since there was no progress since 2022 I would say no, not relevant.

**Pull request closed without merging**
